#!/bin/sh

cat | sqlite3 <<EOF
CREATE TABLE LINEITEM(OKEY INT, PKEY INT, PRICE REAL);
CREATE TABLE PART(PKEY INT, COST REAL);
CREATE TABLE ORDERS(OKEY INT, ZIP INT);

.separator |
.import lineitem.tbl LINEITEM
.import order.tbl ORDERS
.import part.tbl PART

.separator ' '

SELECT ZIP, SUM(PRICE-COST)
FROM LINEITEM L, PART P, ORDERS O
WHERE L.PKEY=P.PKEY AND L.OKEY=O.OKEY
GROUP BY ZIP
ORDER BY ZIP ASC;
EOF
